version: '3.9'
services:

  load_balancer:
    image: haproxy:2.4-alpine
    ports:
    - 8081:8081
    volumes:
    - './haproxy:/usr/local/etc/haproxy'
    depends_on:
      - poc_agent_1
      - poc_agent_2
    networks:
      - poc_agent_network

  go_client:
    image: ubirch/ubirch-client:v1.2.2
    container_name: ubirch_client
    volumes:
      - './uppClient:/data'
    networks:
      - poc_agent_network

  poc_agent_1:
    image: ubirch/ubirch-poc-agent:v0.1.0
    container_name: poc_agent_1
    volumes:
      - './pocAgent:/data'
    depends_on:
      - go_client
    environment:
      - JAVA_OPTS=-XX:+UseContainerSupport -Duser.home=/tmp
      - POC_AGENT_SVC_HTTP_SERVER_PORT=8081
      - POC_AGENT_SVC_HTTP_CLIENT_SSL_KEYSTORE_TYPE=pkcs12
      - POC_AGENT_SVC_HTTP_CLIENT_SSL_KEYSTORE=/data/key_store.p12
      - POC_AGENT_SVC_UPP_ENDPOINT=http://go_client:8080
      - POC_AGENT_SVC_CERTIFY_ENDPOINT=https://api.certify.dev.ubirch.com
      - POC_AGENT_SVC_HTTP_SWAGGER_ACTIVATED=true
    env_file: poc_agent.env
    networks:
      - poc_agent_network
    mem_limit: 1000m
    mem_reservation: 500M
    cpus: 0.5

  poc_agent_2:
    image: ubirch/ubirch-poc-agent:v0.1.0
    container_name: poc_agent_2
    volumes:
      - './pocAgent:/data'
    depends_on:
      - go_client
    environment:
      - JAVA_OPTS=-XX:+UseContainerSupport -Duser.home=/tmp
      - POC_AGENT_SVC_HTTP_SERVER_PORT=8081
      - POC_AGENT_SVC_HTTP_CLIENT_SSL_KEYSTORE_TYPE=pkcs12
      - POC_AGENT_SVC_HTTP_CLIENT_SSL_KEYSTORE=/data/key_store.p12
      - POC_AGENT_SVC_UPP_ENDPOINT=http://go_client:8080
      - POC_AGENT_SVC_CERTIFY_ENDPOINT=https://api.certify.dev.ubirch.com
      - POC_AGENT_SVC_HTTP_SWAGGER_ACTIVATED=true
    env_file: poc_agent.env
    networks:
      - poc_agent_network
    mem_limit: 1000m
    mem_reservation: 500M
    cpus: 0.5

networks:
  poc_agent_network:
